### ISSUE TITLE
Update MRTK3 min version of com.microsoft.mrtk.graphicstools.unity to latest

### ISSUE THREAD

**Issue by IssueSyncBot** [MixedRealityToolkit/MixedRealityToolkit-Unity#101]
### Original issue opened by:
<img class="avatar avatar-user" src="https://avatars.githubusercontent.com/u/36461279?v=4" width="20" height="20" style="border-radius: 50%" alt="@AMollis"> AMollis
___

# Overview
Before GA, we should update MRTK3's min version of com.microsoft.mrtk.graphicstools.unity to latest

# Tasks
- [x] Publish com.microsoft.mrtk.graphicstools.unity latest to our Feature Tool's NPM feed
- [x] Update MRTK3's package dependencies to require com.microsoft.mrtk.graphicstools.unity latest
- [x] Update MRTK3's sample to use com.microsoft.mrtk.graphicstools.unity to latest
- [x] Run manual test pass to valid new graphics tools work for Unity 2021 and 2022

___
### ISSUE MIGRATION

   Issue migrated from: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11584
