### ISSUE TITLE
Fix Example scenes - Cannot move some scene description panels

### ISSUE THREAD

**Issue by IssueSyncBot** [MixedRealityToolkit/MixedRealityToolkit-Unity#104]
### Original issue opened by:
<img class="avatar avatar-user" src="https://avatars.githubusercontent.com/u/9615036?v=4" width="20" height="20" style="border-radius: 50%" alt="@shaynie"> @shaynie
___

## Describe the bug

Other example scenes let you drag the entire scene contents by grabbing the description panel and moving it.  In the Dialog Example scene the description panel is locked in place.

## To reproduce

1. Load the DialogExample/DictationExample scene in the Unity editor
2. Run the scene
3. Using input simulation, note that you cannot select the description panel.

## Expected behavior

The description panel should be interactable and move the scene content.

### Tasks
- [ ] Fix Dictation Sample scene
- [ ] Fix dialog example scene
- [ ] Fix BoundsControl scene
- [ ] Fix Clipping scene
- [ ] Fix any other scenes
- [ ] Non-Canvas Object Bar Example Scene
- [ ] Non-Canvas UI Backplate Example Scene

___
### ISSUE MIGRATION

   Issue migrated from: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11580

**Comment by ghazen-ml** [comment]
In addition to the panels sometimes not being moveable, many also let raycasts through to content behind. It may be nice to add a collider to all of these and then to in addition consider adding ObjectManipulation capability.
