### ISSUE TITLE
Unity Hands API Integration

### ISSUE THREAD

**Issue by IssueSyncBot** [MixedRealityToolkit/MixedRealityToolkit-Unity#207]
### Original issue opened by:
<img class="avatar avatar-user" src="https://avatars.githubusercontent.com/u/5544935?v=4" width="20" height="20" style="border-radius: 50%" alt="@Zee2"> Zee2
___

## Context

Unity has released (is releasing?) a new Hands API. This issue tracks our integration with their new Hands subsystem, API, OpenXR features, etc.

## Todos

- [ ] Evaluate whether we can simply drop-in their Hands subsystem
- [ ] Figure out whether we can make our hands synthesis subsystem a sibling implementation of the new Hands subsystem
- [ ] Take a peek at comparative performance
- [ ] Unity fixes the issues with Holographic Remoting
- [ ] Evaluate how this will affect Snapdragon Spaces (probably no need for their hands subsystem, either!)

___
### ISSUE MIGRATION

   Issue migrated from: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11300
