### ISSUE TITLE
Vive Focus 3 to-do list

### ISSUE THREAD

**Issue by IssueSyncBot** [MixedRealityToolkit/MixedRealityToolkit-Unity#265]
### Original issue opened by:
<img class="avatar avatar-user" src="https://avatars.githubusercontent.com/u/5544935?v=4" width="20" height="20" style="border-radius: 50%" alt="@Zee2"> @Zee2
___

Tracking a todo list for various outstanding issues surrounding Vive Focus 3 support. Interest from the community has been demonstrated (#10849) and it seems we don't have to do much on our end to support it! The main blocker is the ray/pinch polyfills, it seems...

Follow instructions here: https://developer.vive.com/resources/openxr/openxr-mobile/tutorials/unity/getting-started-openxr-mobile/ and make sure to delete the MRTKDevTemplate `manifest.xml`.

- [x] Head tracking + display working already (woohoo!)
- [x] Joints working already (woohoo!)
- [x] Controllers working already (woohoo!)
- [ ] Rendering bug in sample scene (mysterious large black glitchy quad/thing...)
- [ ] Pinch and ray polyfills don't seem to function, but neither does the Vive hand interaction profile
- [ ] Vive Focus 3 conflicts with the Quest-specific android manifest xml we have in our sample scene
- [ ] Passthrough, perchance?

Update Oct 4th: now blocked, as our Vive Focus 3 has been taken away from us :( Will need to find/buy/etc another one...

___
### ISSUE MIGRATION

   Issue migrated from: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10942
