### ISSUE TITLE
Update `XR Rig` prefab to better support HoloLens 2 scenarios

### ISSUE THREAD

**Issue by IssueSyncBot** [MixedRealityToolkit/MixedRealityToolkit-Unity#323]
### Original issue opened by:
<img class="avatar avatar-user" src="https://avatars.githubusercontent.com/u/36461279?v=4" width="20" height="20" style="border-radius: 50%" alt="@AMollis"> AMollis
___

# Overview

We recently hit issues where the default `XR Rig` settings didn't work with Azure Spatial Anchors and Azure Remote Rendering on HoloLens 2.   We should improve the experience for HoloLens 2 so that these scenarios work out of the box.

# Tasks

- [ ] Figure out correct defaults for MRKT3's `XR Rig` prefab.  At the moment `Tracking Origin Mode` is set to `Not Specified` and `Camera Y Offset` set to 1.6.  This doesn't seem ideal for HoloLens2, but perhaps it is correct given the `Transform.Position.Y` value is 1.6.  However, these settings didn't work correctly with ASA and ARR; need to understand why.
- [ ] Update MRTK3's `XR Rig` prefab as needed
- [ ] Maybe create a HoloLens 2 specific `XR Rig` prefab?
- [ ] Add MSFT's [EyeLevelSceneOrigin](https://learn.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.openxr.eyelevelsceneorigin?view=mixedreality-openxr-plugin-1.7) to HL2 specific `XR Rig` prefab?

Current Defaults:

![Image](https://user-images.githubusercontent.com/36461279/228428266-dfcac2a5-b194-4740-b7b5-7d962b11ce52.png)

# More Context
For ASA and ARR to function correctly on HoloLens 2, we had to set `Tracking Origin Mode` to `Device` and `Camera Y Offset` to 0. 

Some useful information from the MSFT OpenXR Team:

> Tracking origin mode sets the origin of XR content in the Unity scene to either be centered in your headset's starting position (Device) or centered on the floor below your starting position (Floor) 
> 
> The Camera Y Offset is how far the camera is translated above that XR origin within the Unity scene. 
> 
> Typically, we do TrackingOriginMode=Device, Camera Y Offset=0, which makes sure the experience starts around your head (assuming the Unity app is built around the origin). The other common (older) configuration I've seen is TrackingOriginMode=Floor, Camera Y Offset=1.6, which places the origin on the floor (roughly) and the camera still where your head is.

Also from OpenXR Team:

> The device mode should be set to "Unbounded" not just "Device".  

The "Device" setting uses "Local" tracking. The MSFT OpenXR plugin has a component to force the app into an "Unbounded" tracking. See the [EyeLevelSceneOrigin](https://learn.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.openxr.eyelevelsceneorigin?view=mixedreality-openxr-plugin-1.7) class for details. Perhaps the MRTK `XR Rig` prefab for HoloLens should use this. 

___
### ISSUE MIGRATION

   Issue migrated from: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11445
