### ISSUE TITLE
[FEATURE REQUEST] Refactor `SliderSounds` to use a single audio source.

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#438]
## Overview

The component at [org.mixedrealitytoolkit.uxcore/Slider/SliderSounds.cs](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/blob/main/org.mixedrealitytoolkit.uxcore/Slider/SliderSounds.cs) has two audio sources, `passNotchAudioSource` and `grabReleaseAudioSource`.  We don't understand why there are two audio sources.

Both `passNotchAudioSource` and `grabReleaseAudioSource` were private non-serialized fields.  However, with the following PR, these fields have been exposed via the inspector window and public properties. 

- https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/pull/436

Marking to this as a "Release Blocker" to avoid shipping an update to "UX Core" without first understanding this issue. To avoid future deprecation, if two audio sources aren't needed, we should not spin a release with these non-private audio sources.

## Tasks

- [ ] Determine if two audio sources are in fact needed.
- [ ] If two audio sources aren't needed, refactor code so that there is only one.
- [ ] If two audio source are needed, close this issue.

## Additional context

Looking at the history of the file (from our internal repository) looks like @MaxWang-MS added the two audio sources when they first created the file.

**Comment by david-c-kline** [comment]
One thing to note is that using a single audio source will cause the grab/release sounds to have their pitch altered based on the position of the slider thumb (the pass notch code sweeps the frequency of the audio source).

If we are ok with that, we can unify the sources, otherwise, we should continue using two.

**Comment by david-c-kline** [comment]
@AMollis, @keveleigh, @shaynie, @ghazen-ml, @whebertML Thoughts?

**Comment by whebertML** [comment]
@david-c-kline @AMollis Perhaps an alternative to exposing that two AudioSources are used internally so as to avoid possible future deprecation if that changes, just expose one serialized AudioSource that the dev can tweak, and internally make a second one for pass notch use and duplicate the settings (like audio mixer group) and keep the benefit of the pitch changes for pass notch?

**Comment by AMollis** [comment]
> One thing to note is that using a single audio source will cause the grab/release sounds to have their pitch altered based on the position of the slider thumb (the pass notch code sweeps the frequency of the audio source).
> 
> If we are ok with that, we can unify the sources, otherwise, we should continue using two.

Could the code reset the pitch to the default value before playing the grab sound?

**Comment by david-c-kline** [comment]
> @david-c-kline Could the code reset the pitch to the default value before playing the grab sound?
> 
> It seems to me that the only reason for having two audio sources is to mix the sounds. If there is a chance the sounds can overlap, then I suppose to audio sources is fine.

I can definitely give that a try.

**Comment by shaynie** [comment]
@david-c-kline Believes he should get to this by the end of 9/30

**Comment by david-c-kline** [comment]
Updated note: Confirmed that the pitch shifting on the second audio source is being done destructively. Will look at caching / restoring based on the user's actions.

**Comment by david-c-kline** [comment]
I have a working fix for this. Considering whether or not to update the slider prefabs to have an AudioSource pre-attached.

**Comment by david-c-kline** [comment]
Decided to update the prefabs in UXComponents and UXComponents.NonCanvas this forces an update to 3.1.0 as well as a reference to UXCore 3.1.0.

No other packages that reference UXCore utilize SliderSounds, so their dependency requirements remain unchanged.
