### ISSUE TITLE
Mid-March Release

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#644]
This is tracking the release of packages in mid-march

**Tasks**
- [ ] Check Package Versions
- [ ] Create Release Branch
- [ ] Create Release Canidate Packages
- [ ] Create Draft Release on GitHub
- [ ] Microsoft Validates Release Canidate Packages and Release Notes
- [ ] Qualcomm Validates Release Canidate Packages and Release Notes
- [ ] Magic Leap Validates Release Canidate Packages and Release Notes
- [ ] Repackage and Publish to NPM Feed
- [ ] Publish GitHub Release
- [ ] Update API Reference Documentation
- [ ] Publish UPM packages to Asset Store

**Comment by AMollis** [comment]
Updating title to [Release] Release MRTK3 packages at commit f279218d1e1f0856ebb32c6122b0b22a273a15d6

**Comment by shaynie** [comment]
Update holodevelopers slack?
