### ISSUE TITLE
Polish new MRTK3 Learning Paths Documenation

### ISSUE THREAD

**Issue by IssueSyncBot** [MixedRealityToolkit/MixedRealityToolkit-Unity#70]
### Original issue opened by:
<img class="avatar avatar-user" src="https://avatars.githubusercontent.com/u/36461279?v=4" width="20" height="20" style="border-radius: 50%" alt="@AMollis"> @AMollis
___

# Overview

The MRTK3 Learning Paths documents  need to be polished.

# Tasks

- [x] Copy documentation changes from https://github.com/microsoft/MixedRealityToolkit-Learning-Paths-Partners to https://github.com/MicrosoftDocs/learn-pr
- [x] Update https://github.com/microsoft/MixedRealityLearning/ to point to new MRTK3 pre-release asset packages (`*.unitypackage`)
- [x] Fix any other bugs in documentation

___
### ISSUE MIGRATION

   Issue migrated from: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11675
