### ISSUE TITLE
[Release] Release a May Update

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#727]
Minimum version of "Package Validation" was updated, requiring shorting package descriptions.   Need to release another version of MRTK so we can publish to Unity Asset Store.

This is tracking the release of packages in mid-march

**Tasks**
- [ ] Check Package Versions
- [ ] Create Release Branch
- [ ] Create Release Canidate Packages
- [ ] Create Draft Release on GitHub
- [ ] Microsoft Validates Release Candidate Packages and Release Notes
- [ ] Qualcomm Validates Release Candidate Packages and Release Notes
- [ ] Magic Leap Validates Release Candidate Packages and Release Notes
- [ ] Ultra Leap Validates Release Candidate Packages and Release Notes
- [ ] Repackage and Publish to NPM Feed
- [ ] Publish GitHub Release
- [ ] Update API Reference Documentation
- [ ] Publish UPM packages to Asset Store

**Optional Tasks**
- [ ] Community Validates Release Candidate Packages (post in Slack and Discussion Forum)

**Comment by sinano1107** [comment]
I am looking forward to using UPM. When is this release likely to be released?
