### ISSUE TITLE
[RELEASE] June public preview release of XRI3 support

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#778]
XRI3 will be ready for public testing. We will release a public preview of the MRTK3 packages that have been updated to support XRI3

This is tracking the release of packages by end of June

**Tasks**
- [ ] Check Package Versions
- [ ] Create Release Branch
- [ ] Create Release Canidate Packages
- [ ] Create Draft Release on GitHub
- [ ] Microsoft Validates Release Candidate Packages and Release Notes
- [ ] Qualcomm Validates Release Candidate Packages and Release Notes
- [ ] Magic Leap Validates Release Candidate Packages and Release Notes
- [ ] Ultra Leap Validates Release Candidate Packages and Release Notes
- [ ] Repackage and Publish to NPM Feed
- [ ] Publish GitHub Release
- [ ] Update API Reference Documentation
- [ ] Publish UPM packages to Asset Store

**Optional Tasks**
- [ ] Community Validates Release Candidate Packages (post in Slack and Discussion Forum)

**Comment by ghazen-ml** [comment]
I tried updating the MagicLeap internal version of the MRTK samples project to use the feature/XRI3 branch (@ 2e7da36c938d53d07575f35863b4aa405730aea2). It seems to be mostly working after performing the upgrade (some automatic and a few minor manual script changes were needed -- there were also complaints about XROrigin not being a parent for ARMeshManagert iirc). 

Two problems I saw so far:

1. I couldn’t scroll the volumetric UI panel in the hand interactions demo — it worked in editor. The ScrollRects in ScrollingExample and VirtualizedScrollRectList seem ok
2. The ray visual for the ML2 controller didn’t always show up -- this is likely internal to the ML2 support pacakge and we'd need to debug

cc @whebertML

**Comment by shaynie** [comment]
Magic leap continuing evaluation week of 7/21/24
Ultraleap checking packages on 7/25/24
Microsoft ongoing testing week of 7/21/24
Quallcomm testing week of 7/29/24.

**Comment by AMollis** [comment]
@shaynie in release notes please log the following:

  - [ ] https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/878
  - [ ] https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/877
  - [ ] https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/876

**Comment by AMollis** [comment]
Release was posted at https://github.com/orgs/MixedRealityToolkit/discussions/894

Still pending releasing to Unity Asset Store
