### ISSUE TITLE
September MRTK3 `main` Release - Unity Asset Store Publication

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#905]
This is tracking the release of `main` by end of September.  The primary purpose of this release is to address failures in UPM Asset Store publication.

**Tasks**
- [ ] Make sure patch versions and CHANGELOGs are updated for the following packages that error'ed during UMP store publishing
   - [ ] MRTK Audio Effects (failed publication @ 3.0.3)
   - [ ] MRTK Core Definitions (failed publication @ 3.2.1)
   - [ ] MRTK Extended Assets (failed publication @ 3.0.2)
   - [ ] MRTK Input (failed publication @ 3.2.1)
   - [ ] MRTK Tools (failed publication @ 3.0.3)
   - [ ] MRTK UX Components (Non-Canvas) (failed publication @ 3.1.3)
   - [ ] MRTK UX Core Scripts (failed publication @ 3.2.1) 
   - [ ] Plus any additional packages with changes in it since last release of `main`
- [ ] Check Package Versions
- [ ] Create Release Branch
- [ ] Create Release Canidate Packages
- [ ] Create Draft Release on GitHub
- [ ] Microsoft Validates Release Candidate Packages and Release Notes
- [ ] Qualcomm Validates Release Candidate Packages and Release Notes
- [ ] Magic Leap Validates Release Candidate Packages and Release Notes
- [ ] Ultra Leap Validates Release Candidate Packages and Release Notes
- [ ] Repackage and Publish to NPM Feed
- [ ] Update documentation
- [ ] Publish UPM packages to Unity Asset Store
- [ ] Publish GitHub Release

**Optional Tasks**
- [ ] Update API Reference Documentation (Not Needed for Public Preview)
- [ ] Community Validates Release Candidate Packages (post in Slack and Discussion Forum)
