### ISSUE TITLE
[XRI3] [RELEASE] [PREVIEW.2] Public preview 2 release of XRI3 support

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#931]
XRI3 will be ready for public testing. We will release a public preview of the MRTK3 packages that have been updated to support XRI3

This is tracking the release of packages by end of June

**Tasks**
- [ ] Check Package Versions
- [ ] Create Release Branch
- [ ] Create Release Canidate Packages
- [ ] Create Draft Release on GitHub
- [ ] Microsoft Validates Release Candidate Packages and Release Notes
- [ ] Qualcomm Validates Release Candidate Packages and Release Notes
- [ ] Magic Leap Validates Release Candidate Packages and Release Notes
- [ ] Ultra Leap Validates Release Candidate Packages and Release Notes
- [ ] Repackage and Publish to NPM Feed
- [ ] Publish UPM packages to Unity Asset Store
- [ ] Publish GitHub Release

**Optional Tasks**
- [ ] Update API Reference Documentation (Not Needed for Public Preview)
- [ ] Community Validates Release Candidate Packages (post in Slack and Discussion Forum)
