### ISSUE TITLE
[Main] [Release] Release packages to address UPM Asset Store failures

### ISSUE THREAD

**Issue by AMollis** [MixedRealityToolkit/MixedRealityToolkit-Unity#932]
This is tracking the release of `main` to address UPM Asset Store Failure.  The primary purpose of this release is to address failures in UPM Asset Store publication.

1. Package dependencies reference versions of packages that aren't in the asset store.  These dependencies need to be updated to point to versions that are in the asset store
2. Address this error message:
![Image](https://github.com/user-attachments/assets/252adbe4-20ae-438a-ae16-fbfdc6673153)

**Tasks**
- [ ] Make sure patch versions and CHANGELOGs are updated for the following packages that error'ed during UMP store publishing
   - [x] MRTK Audio Effects (failed publication @ 3.0.3)
   - [x] MRTK Core Definitions (failed publication @ 3.2.1)
   - [x] MRTK Extended Assets (failed publication @ 3.0.2)
   - [x] MRTK Input (failed publication @ 3.2.1)
   - [x] MRTK Tools (failed publication @ 3.0.3)
   - [x] MRTK UX Components (Non-Canvas) (failed publication @ 3.1.3)
   - [x] MRTK UX Core Scripts (failed publication @ 3.2.1) 
   - [x] Plus any additional packages with changes in it since last release of `main`
- [ ] Check Package Versions
- [ ] Create Release Branch
- [ ] Create Release Canidate Packages
- [ ] Create Draft Release on GitHub
- [ ] Microsoft Validates Release Candidate Packages and Release Notes
- [ ] Qualcomm Validates Release Candidate Packages and Release Notes
- [ ] Magic Leap Validates Release Candidate Packages and Release Notes
- [ ] Ultra Leap Validates Release Candidate Packages and Release Notes
- [ ] Repackage and Publish to NPM Feed
- [ ] Update documentation
- [ ] Publish UPM packages to Unity Asset Store
- [ ] Publish GitHub Release

**Optional Tasks**
- [ ] Update API Reference Documentation (Not Needed for Public Preview)
- [ ] Community Validates Release Candidate Packages (post in Slack and Discussion Forum)

**Comment by AMollis** [comment]
Unity has fixed #2.

For #1 we need to fix up package dependencies to point to versions of the MRTK3 packages that have been published to the store
